// Topic suggestions library — common engineering/CS subjects with subtopics
// Each topic has a default day estimate

export const TOPIC_LIBRARY = [
  {
    id: "ml",
    title: "Machine Learning",
    emoji: "🤖",
    keywords: [
      "ml",
      "machine learning",
      "machine",
      "learning",
      "ai",
      "artificial intelligence",
    ],
    color: "#6366f1",
    topics: [
      { name: "Introduction to ML & Types", days: 1 },
      { name: "Linear Regression", days: 2 },
      { name: "Logistic Regression", days: 2 },
      { name: "Bias-Variance Tradeoff", days: 1 },
      { name: "Gradient Descent & Optimization", days: 2 },
      { name: "Decision Trees", days: 2 },
      { name: "Random Forests & Bagging", days: 2 },
      { name: "Boosting: XGBoost & AdaBoost", days: 3 },
      { name: "Support Vector Machines (SVM)", days: 2 },
      { name: "K-Nearest Neighbors (KNN)", days: 1 },
      { name: "Naive Bayes", days: 1 },
      { name: "K-Means Clustering", days: 2 },
      { name: "DBSCAN & Hierarchical Clustering", days: 2 },
      { name: "Principal Component Analysis (PCA)", days: 2 },
      { name: "Dimensionality Reduction", days: 1 },
      { name: "Cross-Validation & Hyperparameter Tuning", days: 2 },
      { name: "Feature Engineering & Selection", days: 2 },
      { name: "Regularization (L1/L2)", days: 1 },
      { name: "Evaluation Metrics (Precision, Recall, F1)", days: 1 },
      { name: "Neural Networks Basics", days: 3 },
      { name: "Backpropagation", days: 2 },
      { name: "ML Project End-to-End Pipeline", days: 3 },
    ],
  },
  {
    id: "dl",
    title: "Deep Learning",
    emoji: "🧠",
    keywords: [
      "deep learning",
      "deep",
      "dl",
      "neural",
      "neural network",
      "cnn",
      "rnn",
    ],
    color: "#8b5cf6",
    topics: [
      { name: "Perceptron & Activation Functions", days: 1 },
      { name: "Feedforward Neural Networks", days: 2 },
      { name: "Backpropagation & Chain Rule", days: 2 },
      { name: "Optimizers: SGD, Adam, RMSProp", days: 2 },
      { name: "Convolutional Neural Networks (CNN)", days: 3 },
      { name: "CNN Architectures: VGG, ResNet, Inception", days: 3 },
      { name: "Recurrent Neural Networks (RNN)", days: 2 },
      { name: "LSTM & GRU", days: 2 },
      { name: "Attention Mechanism", days: 2 },
      { name: "Transformers Architecture", days: 3 },
      { name: "Transfer Learning & Fine-tuning", days: 2 },
      { name: "GANs (Generative Adversarial Networks)", days: 3 },
      { name: "Autoencoders & VAEs", days: 2 },
      { name: "Batch Normalization & Dropout", days: 1 },
      { name: "Object Detection: YOLO, R-CNN", days: 3 },
      { name: "PyTorch Fundamentals", days: 3 },
      { name: "Model Deployment with ONNX/TensorRT", days: 2 },
    ],
  },
  {
    id: "dsa",
    title: "Data Structures & Algorithms",
    emoji: "⚡",
    keywords: [
      "dsa",
      "data structure",
      "algorithm",
      "algorithms",
      "competitive",
      "cp",
      "leetcode",
      "coding",
    ],
    color: "#f59e0b",
    topics: [
      { name: "Arrays & Strings", days: 2 },
      { name: "Two Pointers & Sliding Window", days: 2 },
      { name: "Hashing & Hash Maps", days: 2 },
      { name: "Linked Lists", days: 2 },
      { name: "Stacks & Queues", days: 2 },
      { name: "Recursion & Backtracking", days: 3 },
      { name: "Binary Search", days: 2 },
      { name: "Sorting Algorithms", days: 2 },
      { name: "Trees: BFS & DFS", days: 3 },
      { name: "Binary Search Trees", days: 2 },
      { name: "Heaps & Priority Queues", days: 2 },
      { name: "Graphs: Representation & Traversal", days: 3 },
      { name: "Shortest Path: Dijkstra, Bellman-Ford", days: 3 },
      { name: "Minimum Spanning Tree: Prim, Kruskal", days: 2 },
      { name: "Topological Sort", days: 1 },
      { name: "Dynamic Programming Basics", days: 3 },
      { name: "DP: Knapsack & Subsequences", days: 3 },
      { name: "DP: Grids & Intervals", days: 3 },
      { name: "Tries", days: 2 },
      { name: "Segment Trees & Fenwick Trees", days: 3 },
      { name: "Union Find (Disjoint Set)", days: 2 },
      { name: "Bit Manipulation", days: 2 },
      { name: "Greedy Algorithms", days: 2 },
    ],
  },
  {
    id: "webdev",
    title: "Web Development",
    emoji: "🌐",
    keywords: [
      "web",
      "webdev",
      "web development",
      "frontend",
      "backend",
      "fullstack",
      "full stack",
      "html",
      "css",
      "javascript",
    ],
    color: "#06b6d4",
    topics: [
      { name: "HTML5 Fundamentals & Semantics", days: 2 },
      { name: "CSS3: Flexbox & Grid", days: 3 },
      { name: "CSS Animations & Transitions", days: 1 },
      { name: "Responsive Design & Media Queries", days: 2 },
      { name: "JavaScript Fundamentals", days: 4 },
      { name: "ES6+: Destructuring, Spread, Modules", days: 2 },
      { name: "Promises & Async/Await", days: 2 },
      { name: "DOM Manipulation & Events", days: 2 },
      { name: "Fetch API & Axios", days: 1 },
      { name: "React: Components & JSX", days: 3 },
      { name: "React: State & Props", days: 2 },
      { name: "React: Hooks (useState, useEffect, custom)", days: 3 },
      { name: "React: Context API & Redux", days: 3 },
      { name: "Next.js: SSR & SSG", days: 3 },
      { name: "TypeScript Basics", days: 3 },
      { name: "Node.js & Express.js", days: 3 },
      { name: "REST API Design", days: 2 },
      { name: "Authentication: JWT & OAuth", days: 2 },
      { name: "SQL & PostgreSQL", days: 3 },
      { name: "MongoDB & Mongoose", days: 2 },
      { name: "Prisma ORM", days: 2 },
      { name: "Testing: Jest & React Testing Library", days: 2 },
      { name: "Web Performance Optimization", days: 2 },
    ],
  },
  {
    id: "devops",
    title: "DevOps & Cloud",
    emoji: "☁️",
    keywords: [
      "devops",
      "cloud",
      "aws",
      "docker",
      "kubernetes",
      "k8s",
      "ci/cd",
      "cicd",
      "infra",
      "infrastructure",
    ],
    color: "#10b981",
    topics: [
      { name: "Linux Fundamentals & Shell Scripting", days: 3 },
      { name: "Git & Git Workflows (GitFlow, trunk-based)", days: 2 },
      { name: "Docker: Images, Containers & Networking", days: 3 },
      { name: "Docker Compose", days: 2 },
      { name: "Kubernetes: Pods, Services & Deployments", days: 4 },
      { name: "Kubernetes: ConfigMaps, Secrets & Volumes", days: 2 },
      { name: "Helm Charts", days: 2 },
      { name: "CI/CD with GitHub Actions", days: 3 },
      { name: "Jenkins Pipelines", days: 2 },
      { name: "AWS Core: EC2, S3, VPC, IAM", days: 4 },
      { name: "AWS: RDS, DynamoDB, ElastiCache", days: 3 },
      { name: "AWS: Lambda & Serverless", days: 2 },
      { name: "Terraform: IaC Basics", days: 3 },
      { name: "Ansible Automation", days: 2 },
      { name: "Monitoring: Prometheus & Grafana", days: 3 },
      { name: "ELK Stack (Elasticsearch, Logstash, Kibana)", days: 3 },
      { name: "Service Mesh: Istio", days: 2 },
      { name: "Site Reliability Engineering (SRE) Concepts", days: 2 },
    ],
  },
  {
    id: "system-design",
    title: "System Design",
    emoji: "🏗️",
    keywords: [
      "system design",
      "system",
      "design",
      "hld",
      "lld",
      "distributed",
      "architecture",
      "scalability",
    ],
    color: "#f97316",
    topics: [
      { name: "Scalability: Vertical vs Horizontal", days: 1 },
      { name: "Load Balancing Strategies", days: 2 },
      { name: "Caching: Redis, Memcached, CDN", days: 2 },
      { name: "Database Sharding & Replication", days: 2 },
      { name: "SQL vs NoSQL Decision", days: 1 },
      { name: "CAP Theorem & Consistency Models", days: 2 },
      { name: "Message Queues: Kafka, RabbitMQ", days: 3 },
      { name: "API Gateway & Rate Limiting", days: 2 },
      { name: "Microservices Architecture", days: 3 },
      { name: "Event-Driven Architecture", days: 2 },
      { name: "Design URL Shortener", days: 2 },
      { name: "Design Twitter/Feed System", days: 3 },
      { name: "Design WhatsApp/Chat System", days: 3 },
      { name: "Design Uber/Ride Sharing", days: 3 },
      { name: "Design YouTube/Video Streaming", days: 3 },
      { name: "Design Search Autocomplete", days: 2 },
      { name: "Low Level Design: SOLID Principles", days: 2 },
      { name: "LLD: Design Patterns", days: 3 },
      { name: "LLD: Design Chess / Parking Lot", days: 2 },
    ],
  },
  {
    id: "dbms",
    title: "Database Management",
    emoji: "🗄️",
    keywords: [
      "database",
      "dbms",
      "sql",
      "db",
      "postgres",
      "mysql",
      "nosql",
      "mongodb",
    ],
    color: "#3b82f6",
    topics: [
      { name: "Relational Model & ER Diagrams", days: 2 },
      { name: "SQL: DDL, DML, DCL", days: 2 },
      { name: "SQL: Joins, Subqueries & CTEs", days: 3 },
      { name: "SQL: Window Functions & Aggregations", days: 2 },
      { name: "Normalization: 1NF to BCNF", days: 2 },
      { name: "Indexing & Query Optimization", days: 3 },
      { name: "Transactions & ACID Properties", days: 2 },
      { name: "Concurrency Control & Locking", days: 2 },
      { name: "Storage Engines & B-Trees", days: 2 },
      { name: "PostgreSQL Advanced Features", days: 2 },
      { name: "MongoDB: Schema Design & Aggregation", days: 2 },
      { name: "Redis: Caching & Data Structures", days: 2 },
      { name: "Database Replication & Sharding", days: 2 },
    ],
  },
  {
    id: "os",
    title: "Operating Systems",
    emoji: "💻",
    keywords: [
      "os",
      "operating system",
      "operating systems",
      "process",
      "kernel",
      "linux internals",
    ],
    color: "#64748b",
    topics: [
      { name: "Process Management & Scheduling", days: 2 },
      { name: "Threads & Concurrency", days: 2 },
      { name: "Synchronization: Mutex, Semaphores", days: 2 },
      { name: "Deadlocks: Detection & Avoidance", days: 2 },
      { name: "Memory Management & Paging", days: 2 },
      { name: "Virtual Memory & Swapping", days: 2 },
      { name: "File Systems", days: 2 },
      { name: "I/O Management", days: 1 },
      { name: "Linux System Calls & Signals", days: 2 },
      { name: "Interprocess Communication (IPC)", days: 2 },
    ],
  },
  {
    id: "cn",
    title: "Computer Networks",
    emoji: "🌍",
    keywords: [
      "networking",
      "networks",
      "cn",
      "computer networks",
      "tcp",
      "ip",
      "http",
      "dns",
      "protocol",
    ],
    color: "#06d6a0",
    topics: [
      { name: "OSI & TCP/IP Model", days: 2 },
      { name: "Physical & Data Link Layer", days: 2 },
      { name: "Network Layer & IP Addressing", days: 2 },
      { name: "Subnetting & CIDR", days: 2 },
      { name: "Routing Protocols: OSPF, BGP", days: 2 },
      { name: "Transport Layer: TCP vs UDP", days: 2 },
      { name: "TCP Flow Control & Congestion Control", days: 2 },
      { name: "DNS, DHCP & NAT", days: 2 },
      { name: "HTTP/1.1, HTTP/2 & HTTP/3", days: 2 },
      { name: "TLS/SSL & HTTPS", days: 2 },
      { name: "WebSockets & gRPC", days: 2 },
      { name: "CDN & Proxy Servers", days: 1 },
      { name: "Network Security: Firewalls & VPN", days: 2 },
    ],
  },
  {
    id: "nlp",
    title: "Natural Language Processing",
    emoji: "💬",
    keywords: [
      "nlp",
      "natural language",
      "text",
      "llm",
      "bert",
      "gpt",
      "language model",
    ],
    color: "#a855f7",
    topics: [
      { name: "Text Preprocessing & Tokenization", days: 2 },
      { name: "Bag of Words & TF-IDF", days: 1 },
      { name: "Word Embeddings: Word2Vec, GloVe", days: 2 },
      { name: "Sequence Models for NLP", days: 2 },
      { name: "Attention & Transformers for NLP", days: 3 },
      { name: "BERT & Pre-trained Models", days: 3 },
      { name: "GPT Architecture & Prompting", days: 2 },
      { name: "Fine-tuning LLMs", days: 3 },
      { name: "RAG: Retrieval Augmented Generation", days: 3 },
      { name: "Named Entity Recognition (NER)", days: 2 },
      { name: "Sentiment Analysis Pipeline", days: 2 },
      { name: "Text Classification & Summarization", days: 2 },
      { name: "LangChain & AI Agents", days: 3 },
    ],
  },
  {
    id: "cybersec",
    title: "Cybersecurity",
    emoji: "🔐",
    keywords: [
      "security",
      "cybersecurity",
      "ethical hacking",
      "hacking",
      "pentest",
      "ctf",
      "infosec",
    ],
    color: "#ef4444",
    topics: [
      { name: "Security Fundamentals & CIA Triad", days: 1 },
      { name: "Cryptography: Symmetric & Asymmetric", days: 2 },
      { name: "Hashing & Digital Signatures", days: 1 },
      { name: "Network Security & Packet Analysis", days: 2 },
      { name: "Web Security: OWASP Top 10", days: 3 },
      { name: "SQL Injection & XSS", days: 2 },
      { name: "Authentication Attacks & Defense", days: 2 },
      { name: "Linux Privilege Escalation", days: 2 },
      { name: "Penetration Testing Methodology", days: 3 },
      { name: "Metasploit & Burp Suite", days: 3 },
      { name: "Reverse Engineering Basics", days: 2 },
      { name: "CTF Strategy & Practice", days: 3 },
    ],
  },
  {
    id: "dsa-cp",
    title: "Competitive Programming",
    emoji: "🏆",
    keywords: [
      "competitive programming",
      "cp",
      "codeforces",
      "codeforces",
      "icpc",
      "competitive",
    ],
    color: "#eab308",
    topics: [
      { name: "Fast I/O & STL Mastery", days: 1 },
      { name: "Number Theory: GCD, Primes, Modular Arithmetic", days: 3 },
      { name: "Combinatorics & Probability", days: 2 },
      { name: "Matrix Exponentiation", days: 2 },
      { name: "Advanced Graph: Bridges, Articulation Points", days: 3 },
      { name: "Network Flow: Max Flow, Min Cut", days: 3 },
      { name: "Convex Hull & Geometry", days: 3 },
      { name: "Square Root Decomposition", days: 2 },
      { name: "Heavy-Light Decomposition", days: 3 },
      { name: "Centroid Decomposition", days: 3 },
      { name: "String: KMP, Z-function, Aho-Corasick", days: 3 },
      { name: "Suffix Arrays & Suffix Trees", days: 3 },
      { name: "Game Theory: Nim & Sprague-Grundy", days: 2 },
    ],
  },
  {
    id: "react",
    title: "React.js",
    emoji: "⚛️",
    keywords: ["react", "reactjs", "react.js", "jsx", "hooks"],
    color: "#38bdf8",
    topics: [
      { name: "JSX & Component Basics", days: 1 },
      { name: "Props & State Management", days: 2 },
      { name: "useState & useEffect", days: 2 },
      { name: "useRef, useMemo & useCallback", days: 2 },
      { name: "Custom Hooks", days: 2 },
      { name: "Context API", days: 2 },
      { name: "React Router", days: 2 },
      { name: "Redux Toolkit", days: 3 },
      { name: "Zustand & Jotai", days: 2 },
      { name: "React Query / TanStack Query", days: 2 },
      { name: "Form Handling: React Hook Form", days: 2 },
      { name: "Performance: Code Splitting & Lazy Loading", days: 2 },
      { name: "Testing React Components", days: 2 },
    ],
  },
  {
    id: "python",
    title: "Python",
    emoji: "🐍",
    keywords: ["python", "py", "django", "flask", "fastapi"],
    color: "#fbbf24",
    topics: [
      { name: "Python Syntax & Data Types", days: 2 },
      { name: "Functions, Lambdas & Closures", days: 1 },
      { name: "OOP in Python", days: 2 },
      { name: "Iterators, Generators & Decorators", days: 2 },
      { name: "File I/O & Exception Handling", days: 1 },
      { name: "Modules & Virtual Environments", days: 1 },
      { name: "NumPy & Pandas", days: 3 },
      { name: "Matplotlib & Seaborn", days: 2 },
      { name: "FastAPI Basics", days: 2 },
      { name: "Django ORM & Models", days: 3 },
      { name: "Asyncio & Concurrency", days: 2 },
      { name: "Testing with pytest", days: 2 },
    ],
  },
  {
    id: "java",
    title: "Java",
    emoji: "☕",
    keywords: ["java", "jvm", "spring", "spring boot", "maven", "gradle"],
    color: "#f97316",
    topics: [
      { name: "Java Syntax & OOP Fundamentals", days: 3 },
      { name: "Collections Framework", days: 2 },
      { name: "Generics & Type Safety", days: 2 },
      { name: "Streams & Functional Programming", days: 2 },
      { name: "Concurrency: Threads & ExecutorService", days: 3 },
      { name: "JVM Internals & Garbage Collection", days: 2 },
      { name: "Spring Core & Dependency Injection", days: 3 },
      { name: "Spring Boot & REST APIs", days: 3 },
      { name: "Spring Data JPA & Hibernate", days: 3 },
      { name: "Spring Security", days: 2 },
      { name: "Microservices with Spring Cloud", days: 3 },
      { name: "Testing: JUnit & Mockito", days: 2 },
    ],
  },
  {
    id: "blockchain",
    title: "Blockchain & Web3",
    emoji: "⛓️",
    keywords: [
      "blockchain",
      "web3",
      "ethereum",
      "solidity",
      "crypto",
      "smart contract",
      "defi",
    ],
    color: "#8b5cf6",
    topics: [
      { name: "Blockchain Fundamentals & Consensus", days: 2 },
      { name: "Bitcoin: UTXO Model & Mining", days: 2 },
      { name: "Ethereum & EVM Architecture", days: 2 },
      { name: "Solidity: Basics & Data Types", days: 2 },
      { name: "Solidity: Functions, Events & Modifiers", days: 2 },
      { name: "Smart Contract Patterns", days: 2 },
      { name: "Hardhat & Foundry Testing", days: 2 },
      { name: "DeFi: AMMs, Lending Protocols", days: 3 },
      { name: "NFTs & ERC Standards", days: 2 },
      { name: "Web3.js & Ethers.js", days: 2 },
      { name: "Smart Contract Security & Auditing", days: 3 },
      { name: "Layer 2: Rollups & ZK Proofs", days: 3 },
    ],
  },
  {
    id: "data-science",
    title: "Data Science",
    emoji: "📊",
    keywords: [
      "data science",
      "data analysis",
      "analytics",
      "statistics",
      "eda",
      "visualization",
    ],
    color: "#0ea5e9",
    topics: [
      { name: "Statistics: Descriptive & Inferential", days: 3 },
      { name: "Probability Theory", days: 2 },
      { name: "Hypothesis Testing & p-values", days: 2 },
      { name: "Exploratory Data Analysis (EDA)", days: 2 },
      { name: "Data Cleaning & Wrangling with Pandas", days: 3 },
      { name: "Data Visualization with Seaborn/Plotly", days: 2 },
      { name: "Feature Engineering", days: 2 },
      { name: "SQL for Data Analysis", days: 2 },
      { name: "A/B Testing", days: 2 },
      { name: "Time Series Analysis", days: 3 },
      { name: "Dashboard Building: Tableau/Power BI", days: 3 },
      { name: "Storytelling with Data", days: 1 },
    ],
  },
];

/**
 * Search library entries by a query string
 * Returns matching library entries sorted by relevance
 */
export function searchLibrary(query) {
  if (!query || query.trim().length < 2) return [];
  const q = query.toLowerCase().trim();
  return TOPIC_LIBRARY.filter(
    (entry) =>
      entry.keywords.some((kw) => kw.includes(q) || q.includes(kw)) ||
      entry.title.toLowerCase().includes(q),
  ).slice(0, 5);
}
